name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Plan and Apply Task1
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task1
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan 
        working-directory: ${{ github.workspace }}

      - name: Configure with Ansible
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task2
          ansible-playbook -kK docker-iptable.yaml -kK

      - name: Build and Push Docker Image
        run: |
          docker build -t your-docker-image-name .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-image-name

      - name: Deploy
        run: |
          # Perform deployment actions here
          # e.g., deploy to a Kubernetes cluster or VM

