name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Plan and Apply Task1
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task1
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan 
        working-directory: ${{ github.workspace }}

      - name: Configure with Ansible
        env:
         ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task2
          ansible-playbook -kK docker-iptable.yaml --become -kK

      - name: Build and Push Docker Image
        run: |
          sudo docker build -t test .
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker push test


