name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Plan and Apply Task1
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task1
          terraform init
          terraform apply -auto-approve  
        working-directory:  /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task1

      - name: Configure with Ansible
        env:
         ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
         ANSIBLE_BECOME_PASSWORD: ${{ secrets.ANSIBLE_BECOME_PASSWORD }}
         ADDITIONAL_PASSWORD: ${{ secrets.ADDITIONAL_PASSWORD }}
        run: |
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task2
          ansible-playbook docker-iptable.yaml -i inventory.ini --user=arya --extra-vars "ansible_sudo_pass=${{ secrets.ADDITIONAL_PASSWORD }}"

      - name: Build and Push Docker Image
        run: |        
          cd /home/admin/actions-runner/_work/Devops-Projects/Devops-Projects//Project1/task2     
          sudo docker build -t test .
          sudo docker run -d -p 443:443 test


